name: UltimateBans
version: ${project.version}
main: me.acablade.ultimatebans.UltimateBans
api-version: 1.16
authors: [Acablade]
description: kool ban plugin epic
website: https://www.github.com/Acablade
commands:
  ban:
    description: Ban command for UltimateBans plugin
  tempban:
    aliases: [tban, tb]
    description: Temporary ban command for UltimateBans plugin
  baninfo:
    aliases: [bi,binfo]
    description: Ban info with GUI for UltimateBans plugin
permissions:
  ultimatebans.ban:
    description: Permission to use command "/ban"
  ultimatebans.tempban:
    description: Permission to use command "/tempban"
  ultimatebans.mute:
    description: Permission to use command "/mute"
  ultimatebans.tempmute:
    description: Permission to use command "/tempmute"
